title: David Montalvo
owner: David Montalvo
email: contacto@davidmontalvo.xyz
description: A simple and minimalistic jekyll web
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://davidmontalvo.xyz" # the base hostname & protocol for your site, e.g. http://example.com
language: en
twitter_username: "@david_montalvoo"
github_username: david-montalvoo
disqus_username:
# Build settings
markdown: kramdown
theme: minima

permalink: /:year/:month/:day/:title/

plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/bundle
excerpt_separator: <!--more-->
